default:
  image: node:16.16.0

variables:
  VERCEL_ORG_ID: $VERCEL_ORG_ID

stages:
  - deploy-backend
  - install-build-frontend
  - deploy-frontend

Deployment:
  image: ruby:latest
  stage: deploy-backend
  before_script:
    - gem install dpl
    - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
  script:
    - dpl --provider=heroku --app=$HEROKU_APPNAME --api-key=$HEROKU_APIKEY
    - export HEROKU_API_KEY=$HEROKU_APIKEY
    - heroku run --app $HEROKU_APPNAME python manage.py migrate
  environment:
    name: main
    url: $HEROKU_APP_HOST
  only:
    - main

Install:
  stage: install-build-frontend
  needs: []
  script:
    - cd frontend
    - npm ci --cache .npm --prefer-offline --progress=false --no-audit
    - npm i jest --save-dev --quiet
    - npm run build
  cache:
    paths:
      - .next/

Deploy:
  stage: deploy-frontend
  environment:
    name: production
  variables:
    VERCEL_PROJECT_ID: $VERCEL_PROJECT_ID
  script:
    - cd frontend
    - npm i -g vercel
    - vercel --confirm -t $VERCEL_TOKEN --prod
  only:
  - main
